
text: 根据需求文案，写出测试点，请用json字符串形式返回

promptTemplate: 请从功能角度, 大的方向参考功能测试8大方法，符合条件的点细分;从用户使用角度，根据用户使用场景，符合条件的点细分;小的方向，根据需求提供的事物自特点，自身结构，自身与其他主要事物关联;

format: 格式要求为：一个场景模块有一个或多个测试点，同一个模块测试点列表整合，测试点又分正向测试点，反向测试点，一个模块为一个json,一个测试点带有正向和反向的也是一个json,多个场景模块用json格式整合后输出

Business:
  - app项目
  - web项目
  - pc项目
  - api项目

scenes:
  - 后台业务
  - web产品官网
  - 支付业务
  - 订单业务
  - 优惠业务
  - 广告业务
  - 数据统计业务


testcasePrompt: 根据测试点，写出详细的测试用例,按照：测试模块，用例等级，标题，前置条件，操作步骤，预期结果，同一个模块用例用列表整合，最后用一个json输出