
text: 根据需求文案，写出测试点，

promptTemplate: 请从功能角度, 大的方向参考功能测试8大方法，符合条件的点细分;从用户使用角度，根据用户使用场景，符合条件的点细分;小的方向，根据需求提供的事物自特点，自身结构，自身与其他主要事物关联;

format: |
  格式要求为：一个场景模块有一个或多个测试点，同一个模块多个测试点列表整合，测试点又分正向一个或多个测试点，反向一个或多个测试点,测试点要求精简，长度保持50中文字符左右，描述清晰，
  请严格按照以下 JSON 模板输出（确保括号匹配、语法规范）：
  {
    "需求名称XXX": [
      {
        "模块名称XXX": [
          {
            "测试点名称XXX": [
              {
                "场景名称XXX(正向)": "..."
              },
              {
                "场景名称XXX(反向)": "..."
              }
            ]
          }
        ]
      }
    ]
  }

Business:
  - app项目
  - web项目
  - pc项目
  - api项目

scenes:
  - 后台业务
  - web产品官网
  - 支付业务
  - 订单业务
  - 优惠业务
  - 广告业务
  - 数据统计业务


testcasePrompt: 根据测试点，写出详细的测试用例,按照：测试模块，用例等级，标题，前置条件，操作步骤，预期结果，同一个模块用例用列表整合，最后用一个json输出