DEEPSEEK_API_KEY: sk-5822942360b0414eae1134f5b5aaa69a



OUTPUT_JSON_PATH: "D:/AIGeneration/testcase/xmind_output.json"
DEFAULT_TEMPLATE_PATH: "D:/AIGeneration/testcase/template.xmind"
TEMPLATE_PATH: "D:/AIGeneration/testcase/blank_template.xmind"
TEST_XMIND_PATH: "D:/AIGeneration/testcase/测试用例.xmind"
TEMPLATE_XMIND_PATH: "C:/Users/admin/Desktop/test.xmind"
TESTCASE_JSON_PATH: "D:/AIGeneration/testcase/output.json"
OUTPUT_XLSX_PATH: "D:/AIGeneration/testcase/AI_Generated_Test_Cases.xlsx"
CONVERTED_TESTCASES_JSON_PATH: "D:/AIGeneration/testcase/converted_testcases.json"
