CONVERTED_TESTCASES_JSON_PATH: D:/AIGeneration/testcase/converted_testcases.json
DEEPSEEK_API_KEY: sk-5822942360b0414eae1134f5b5aaa69a
DEFAULT_TEMPLATE_PATH: D:/AIGeneration/testcase/template.xmind
IMG_PATH: D:/AIGeneration/config/de.png
OUTPUT_JSON_PATH: D:/AIGeneration/testcase/xmind_output.json
TEMPLATE_PATH: D:/AIGeneration/testcase/blank_template.xmind
TEMPLATE_XMIND_PATH: C:/Users/admin/Desktop/test.xmind
TESTCASE_JSON_PATH: D:/AIGeneration/testcase/output.json
TEST_POINT_XMIND_FILE: ''
TEST_XMIND_PATH: D:/AIGeneration/testcase/测试用例.xmind
